name: ci-win

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: windows-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest tests 

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml 

      - name: Build documentation
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          poetry run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages/        
      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
